/ C19: the run stops when it has learned what it can. loaded by t/run.q
r:.qc.chk[q;.qc.bool;{1b}]
.t.t["exhausted: bool is two inputs"; (r`ok) and (2=r`n) and `exhausted=r`stop]
.t.t["exhausted: a pair of bools is four"; 4=(.qc.chk[q;(.qc.bool;.qc.bool);{[a;b] 1b}])`n]
.t.t["exhausted: elem til 10 is ten; with a budget of 5 it samples"; (10=(.qc.chk[q;.qc.elem til 10;{1b}])`n) and `n=(.qc.chk[q,enlist[`n]!enlist 5;.qc.elem til 10;{1b}])`stop]
.t.t["exhausted: a budget of 5 samples five"; 5=(.qc.chk[q,enlist[`n]!enlist 5;.qc.elem til 10;{1b}])`n]
r:.qc.chk[q,enlist[`n]!enlist 1000;.qc.t"x";{1b}]
.t.t["exhausted: every byte, given the budget"; (256=r`n) and `exhausted=r`stop]
r:.qc.chk[q;42;{x=42}]
.t.t["exhausted: a constant spec is one input"; (`exhausted=r`stop) and 1=r`n]
/ the choice tree: structure that depends on earlier choices is enumerated too
r:.qc.chk[q;.qc.one (.qc.bool;.qc.int 0 9);{1b}]
.t.t["tree: an alternative is exhausted (one of bool, int 0 9: 2+10 inputs)"; (`exhausted=r`stop) and (12=r`n) and .qc.TR[0;`x]]
r:.qc.chk[q;.qc.lst[0 3] .qc.bool;{.qc.collect x; 1b}]
.t.t["tree: every list of up to three bools once (15)"; (`exhausted=r`stop) and (15=r`n) and (15=count r`cover) and all 1=exec n from r`cover]
r:.qc.chk[q;.qc.lst[0 3] .qc.bool;{x~asc x}]
.t.t["tree: a failure in a value-dependent space shrinks to the minimum"; (`fail=r`stop) and 10b~r[`x]`x]
stS:([]v:`long$()); stcmds:([cmd:`push`pop] pre:({1b};{0<count x}); gen:({.qc.int 0 1};{::}); run:({`stS insert enlist x;};{r:last stS`v; delete from `stS where i=count[stS]-1; r}); post:({[m;i;o] 1b};{[m;i;o] o=last m}); upd:({[m;i;o] m,i};{[m;i;o] -1_m}))
r:.qc.chk[q,enlist[`n]!enlist 1000;.qc.sm[`m0`init`steps!(`long$();{stS::0#stS};0 3)] stcmds;{.qc.collect x`cmd; 1b}]
.t.t["tree: a small state machine is exhausted (every trace of up to three steps: 25, seven command sequences)"; (`exhausted=r`stop) and (25=r`n) and 7=count r`cover]
r:.qc.chk[q;.qc.lst[0 3] .qc.int 0 9;{1b}]
.t.t["not claimed: a path whose product of widths exceeds the budget switches the run to sampling"; (`n=r`stop) and 100=r`n]
stk:0; stg:{stk+:1; $[stk mod 2; .qc.draw .qc.bool; .qc.draw .qc.int 0 9]}
r:.qc.chk[q;stg;{1b}]
.t.t["not claimed: a structure that depends on something other than the choices contradicts the tree; the run samples"; (`n=r`stop) and (100=r`n) and not .qc.TR[0;`x]]
r:.qc.chk[q;42;{x=42}]
.t.t["tree: reset per run (a constant spec leaves one concluded node and no edges)"; (1=count .qc.TR) and .qc.TR[0;`x] and (`pass=.qc.TR[0;`c]) and 1=count .qc.TX]
r:.qc.chk[q;.qc.int 0 9;{x<3}]
.t.t["enumeration order: the first failure is the minimal one, found after 3 passing inputs, 0 shrinks"; (3~r[`x]`x) and (0=r`shrinks) and (3=r`n) and `fail=r`stop]
r:.qc.chk[q;(.qc.int 0 3;.qc.bool);{[a;b] .qc.collect (a;b); 1b}]
.t.t["enumeration: every input exactly once"; (8=r`n) and (8=count r`cover) and all 1=exec n from r`cover]
r:.qc.chk[q;::;{n:.qc.draw .qc.int 1 9; n>0}]
.t.t["interactive draws exhaust too"; (9=r`n) and `exhausted=r`stop]
/ coverage: extend past the budget until confident, up to nmax
r:.qc.chk[q;.qc.elem til 1000;{.qc.cover[`most;90;x<950]; 1b}]
.t.t["cover: an open question extends the run and settles (95% vs 90)"; (r`ok) and (`cover=r`stop) and (r[`n]>100) and r[`n]<1000]
r:.qc.chk[q;.qc.elem til 1000;{.qc.cover[`most;90;x<800]; 1b}]
.t.t["cover: a confident shortfall is decided at the budget (80% vs 90)"; (`cover=r`why) and (100=r`n) and `n=r`stop]
r:.qc.chk[q;.qc.elem til 1000;{.qc.cover[`most;90;x<910]; 1b}]
.t.t["cover: a question on the line extends the run and passes, settled or not (a 90% rate decides by chance ~1 run in 20)"; (r`ok) and (r[`stop] in `nmax`cover) and (r[`n]>100) and r[`n]<=1000]
r:.qc.chk[q;.qc.int 0 999;{.qc.cover[`never;1;0b]; 1b}]
.t.t["cover: a never-hit 1% requirement becomes a confident shortfall with more tests"; (`cover=r`why) and (`cover=r`stop) and r[`n]>100]
r:.qc.chk[q;.qc.int 0 9;{.qc.cover[`never;1;0b]; 1b}]
.t.t["cover: an exhausted space cannot extend and passes when it cannot tell"; (r`ok) and `exhausted=r`stop]
r:.qc.chk[q,enlist[`nmax]!enlist 300;.qc.elem til 1000;{.qc.cover[`most;90;x<910]; 1b}]
.t.t["cover: nmax caps the extension"; (r[`n]>100) and r[`n]<=300]
.t.t["stop is always present"; all `stop in/: key each (.qc.chk[q;.qc.int 0 9;{x<3}];.qc.chk[q;.qc.such[{0b}] .qc.int 0 9;{1b}];.qc.recheck[.qc.int 0 9;{1b};enlist 4])]
.t.t["checks reports stop"; `stop in cols .qc.chks[q;enlist[`b]!enlist (.qc.bool;{1b})]]
